# Generated by Django 4.2.6 on 2025-01-03 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=512)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('ismn', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=512)),
                ('genero', models.CharField(max_length=512)),
                ('release_date', models.DateField()),
                ('duracao', models.CharField(max_length=512)),
                ('artista_que_publicou', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('idade', models.IntegerField()),
                ('morada', models.CharField(max_length=512)),
                ('mail', models.CharField(max_length=512, unique=True)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('utilizador_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('nome_artistico', models.CharField(max_length=512)),
                ('pais_origem', models.CharField(max_length=512)),
                ('utilizador_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.utilizador')),
                ('administrador_utilizador_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('utilizador_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.utilizador')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=512)),
                ('music_ismn', models.ForeignKey(db_column='music_ismn', on_delete=django.db.models.deletion.PROTECT, to='app.music')),
                ('consumidor_utilizador_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.consumidor')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_ismn', models.ForeignKey(db_column='music_ismn', on_delete=django.db.models.deletion.PROTECT, to='app.music')),
                ('playlist_playlist', models.ForeignKey(db_column='playlist_playlist_id', on_delete=django.db.models.deletion.PROTECT, to='app.playlist')),
            ],
            options={
                'unique_together': {('playlist_playlist', 'music_ismn')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='consumidor_utilizador_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.consumidor'),
        ),
        migrations.CreateModel(
            name='AlbumMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.PROTECT, to='app.album')),
                ('music_ismn', models.ForeignKey(db_column='music_ismn', on_delete=django.db.models.deletion.PROTECT, to='app.music')),
            ],
            options={
                'unique_together': {('album_id', 'music_ismn')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artista_utilizador_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.artista'),
        ),
        migrations.CreateModel(
            name='Top10',
            fields=[
                ('consumidor_utilizador_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.consumidor')),
                ('playlist_playlist', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='CommentComment',
            fields=[
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.comment')),
                ('comment_id1', models.ForeignKey(db_column='comment_id1', on_delete=django.db.models.deletion.PROTECT, related_name='commentcomment_comment_id1_set', to='app.comment')),
            ],
            options={
                'unique_together': {('comment', 'comment_id1')},
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('play_count', models.IntegerField()),
                ('last_time', models.DateField()),
                ('music_ismn', models.OneToOneField(db_column='music_ismn', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.music')),
                ('consumidor_utilizador_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.consumidor')),
            ],
            options={
                'unique_together': {('music_ismn', 'consumidor_utilizador_user')},
            },
        ),
        migrations.CreateModel(
            name='ArtistaMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_ismn', models.ForeignKey(db_column='music_ismn', on_delete=django.db.models.deletion.PROTECT, to='app.music')),
                ('artista_utilizador_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.artista')),
            ],
            options={
                'unique_together': {('artista_utilizador_user', 'music_ismn')},
            },
        ),
    ]
