# Generated by Django 4.2.6 on 2025-01-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alteracoes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentcomment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commentcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentcomment',
            name='comment_id1',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentComment',
        ),
    ]
