# Generated by Django 5.1.3 on 2025-01-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_commentcomment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name_plural': 'Álbuns'},
        ),
        migrations.AlterModelOptions(
            name='albummusic',
            options={'verbose_name_plural': 'Músicas dos álbuns'},
        ),
        migrations.AlterModelOptions(
            name='artista',
            options={'verbose_name_plural': 'Artistas'},
        ),
        migrations.AlterModelOptions(
            name='artistamusic',
            options={'verbose_name_plural': 'Músicas dos artistas'},
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='consumidor',
            options={'verbose_name_plural': 'Consumidores'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name_plural': 'Músicas'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name_plural': 'Playlists'},
        ),
        migrations.AlterModelOptions(
            name='playlistmusic',
            options={'verbose_name_plural': 'Músicas das playlists'},
        ),
        migrations.AlterModelOptions(
            name='top10',
            options={'verbose_name_plural': 'Top 10s'},
        ),
        migrations.AlterModelOptions(
            name='utilizador',
            options={'verbose_name_plural': 'Utilizadores'},
        ),
    ]
