# Generated by Django 4.2.6 on 2025-01-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_administrador_options_alter_album_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albummusic',
            options={'verbose_name_plural': 'Músicas dos álbuns'},
        ),
        migrations.AlterModelOptions(
            name='artistamusic',
            options={'verbose_name_plural': 'Músicas dos artistas'},
        ),
        migrations.AlterModelOptions(
            name='playlistmusic',
            options={'verbose_name_plural': 'Músicas das playlists'},
        ),
    ]
